// ARCANA Official Preset — D&D 5e (SRD)
// Fully compliant with Bible Section 6

import type { SystemDefinition } from '@/types';

export const dnd5eSystem: SystemDefinition = {
  id: 'dnd5e',
  name: 'Dungeons & Dragons 5e (SRD)',
  version: '5.1.0',
  author: 'Wizards of the Coast (SRD) / ARCANA',
  icon: '🐉',
  color: '#dc2626',
  description: 'O maior RPG de fantasia do mundo. Foco em d20 + modificador + proficiência, classes e magia.',
  builtin: true,
  rollConvention: 'd20',

  attributes: [
    {
      id: 'level',
      name: 'Nível',
      shortName: 'NÍV',
      type: 'number',
      category: 'Geral',
      defaultValue: 1,
      min: 1,
      max: 20,
      description: 'Nível total do personagem.',
    },
    {
      id: 'str',
      name: 'Força',
      shortName: 'FOR',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
      description: 'Poderio físico, atletismo e ataque corpo a corpo.',
    },
    {
      id: 'dex',
      name: 'Destreza',
      shortName: 'DES',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
      description: 'Agilidade, reflexos, equilíbrio e furtividade.',
    },
    {
      id: 'con',
      name: 'Constituição',
      shortName: 'CON',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
      description: 'Saúde, vigor e vitalidade.',
    },
    {
      id: 'int',
      name: 'Inteligência',
      shortName: 'INT',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
      description: 'Acuidade mental, memória e estudo arcano.',
    },
    {
      id: 'wis',
      name: 'Sabedoria',
      shortName: 'SAB',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
      description: 'Percepção, intuição e sintonia com o mundo.',
    },
    {
      id: 'cha',
      name: 'Carisma',
      shortName: 'CAR',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
      description: 'Força de personalidade, magnetismo e persuasão.',
    },
    // Derived Modifiers
    {
      id: 'mod_str',
      name: 'Mod. Força',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((str - 10) / 2)',
    },
    {
      id: 'mod_dex',
      name: 'Mod. Destreza',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((dex - 10) / 2)',
    },
    {
      id: 'mod_con',
      name: 'Mod. Constituição',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((con - 10) / 2)',
    },
    {
      id: 'mod_int',
      name: 'Mod. Inteligência',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((int - 10) / 2)',
    },
    {
      id: 'mod_wis',
      name: 'Mod. Sabedoria',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((wis - 10) / 2)',
    },
    {
      id: 'mod_cha',
      name: 'Mod. Carisma',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((cha - 10) / 2)',
    },
    {
      id: 'proficiency_bonus',
      name: 'Bônus de Proficiência',
      type: 'derived',
      category: 'Geral',
      defaultValue: 2,
      hookFn: `const lvl = Number(attr.level) || 1;
if (lvl >= 17) return 6;
if (lvl >= 13) return 5;
if (lvl >= 9) return 4;
if (lvl >= 5) return 3;
return 2;`,
    },
    {
      id: 'armor_class',
      name: 'Classe de Armadura (CA)',
      type: 'derived',
      category: 'Combate',
      defaultValue: 10,
      formula: '10 + mod_dex',
    },
    {
      id: 'speed',
      name: 'Deslocamento (m)',
      type: 'number',
      category: 'Geral',
      defaultValue: 9,
    },
  ],

  skills: [
    { id: 'acrobatics', name: 'Acrobacia', baseAttribute: 'dex', type: 'proficiency' },
    { id: 'animal_handling', name: 'Lidar com Animais', baseAttribute: 'wis', type: 'proficiency' },
    { id: 'arcana', name: 'Arcanismo', baseAttribute: 'int', type: 'proficiency' },
    { id: 'athletics', name: 'Atletismo', baseAttribute: 'str', type: 'proficiency' },
    { id: 'deception', name: 'Enganação', baseAttribute: 'cha', type: 'proficiency' },
    { id: 'history', name: 'História', baseAttribute: 'int', type: 'proficiency' },
    { id: 'insight', name: 'Intuição', baseAttribute: 'wis', type: 'proficiency' },
    { id: 'intimidation', name: 'Intimidação', baseAttribute: 'cha', type: 'proficiency' },
    { id: 'investigation', name: 'Investigação', baseAttribute: 'int', type: 'proficiency' },
    { id: 'medicine', name: 'Medicina', baseAttribute: 'wis', type: 'proficiency' },
    { id: 'nature', name: 'Natureza', baseAttribute: 'int', type: 'proficiency' },
    { id: 'perception', name: 'Percepção', baseAttribute: 'wis', type: 'proficiency' },
    { id: 'performance', name: 'Atuação', baseAttribute: 'cha', type: 'proficiency' },
    { id: 'persuasion', name: 'Persuasão', baseAttribute: 'cha', type: 'proficiency' },
    { id: 'religion', name: 'Religião', baseAttribute: 'int', type: 'proficiency' },
    { id: 'sleight_of_hand', name: 'Prestidigitação', baseAttribute: 'dex', type: 'proficiency' },
    { id: 'stealth', name: 'Furtividade', baseAttribute: 'dex', type: 'proficiency' },
    { id: 'survival', name: 'Sobrevivência', baseAttribute: 'wis', type: 'proficiency' },
  ],

  resources: [
    {
      id: 'hp',
      name: 'Pontos de Vida',
      maxFormula: '10 + mod_con + (level - 1) * (6 + mod_con)',
      defaultValue: 10,
      color: '#ef4444',
      type: 'bar',
    },
    {
      id: 'inspiration',
      name: 'Inspiração',
      maxFormula: 1,
      defaultValue: 0,
      color: '#f59e0b',
      type: 'checkbox',
    },
  ],

  combat: {
    initiativeFormula: '1d20 + mod_dex',
    hpResource: 'hp',
    defenseStat: {
      name: 'Classe de Armadura (CA)',
      formula: '10 + mod_dex',
    },
    conditions: [
      { id: 'blinded', name: 'Cego', color: '#6b7280' },
      { id: 'charmed', name: 'Enfeitiçado', color: '#ec4899' },
      { id: 'frightened', name: 'Amedrontado', color: '#a855f7' },
      { id: 'paralyzed', name: 'Paralisado', color: '#eab308' },
      { id: 'poisoned', name: 'Envenenado', color: '#22c55e' },
      { id: 'prone', name: 'Caído', color: '#64748b' },
      { id: 'stunned', name: 'Atordoado', color: '#3b82f6' },
      { id: 'unconscious', name: 'Inconsciente', color: '#1e293b' },
    ],
    deathSaves: {
      name: 'Salvaguarda contra Morte',
      formula: '1d20',
      success: 10,
      failure: 9,
    },
  },

  diceMacros: [
    { id: 'd20_check', name: 'Teste d20 Simples', expression: '1d20' },
    { id: 'd20_adv', name: 'Vantagem (2d20kh1)', expression: '2d20kh1' },
    { id: 'd20_dis', name: 'Desvantagem (2d20kl1)', expression: '2d20kl1' },
    { id: 'dnd_attrs', name: 'Rolar Atributo (4d6kh3)', expression: '4d6kh3' },
  ],

  rollPresets: [
    { id: 'init', name: 'Iniciativa', expression: '1d20 + $mod_dex' },
    { id: 'attack_str', name: 'Ataque FOR', expression: '1d20 + $mod_str + $proficiency_bonus' },
    { id: 'attack_dex', name: 'Ataque DES', expression: '1d20 + $mod_dex + $proficiency_bonus' },
  ],

  itemCategories: ['Arma', 'Armadura', 'Escudo', 'Poção', 'Pergaminho', 'Anel', 'Equipamento Geral'],
  createdAt: Date.now(),
  updatedAt: Date.now(),
};
