// ARCANA Official Preset — Ordem Paranormal RPG
// Fully compliant with Bible Section 6

import type { SystemDefinition } from '@/types';

export const ordemParanormalSystem: SystemDefinition = {
  id: 'ordem-paranormal',
  name: 'Ordem Paranormal RPG',
  version: '1.2.0',
  author: 'Cellbit / Jambô / ARCANA',
  icon: '👁️',
  color: '#8b5cf6',
  description: 'Investigação e horror cósmico contemporâneo. Agentes da Ordem investigando o Outro Lado e os 4 elementos arcanos.',
  builtin: true,
  rollConvention: 'd20',

  attributes: [
    {
      id: 'nex',
      name: 'NEX (%)',
      shortName: 'NEX',
      type: 'number',
      category: 'Geral',
      defaultValue: 5,
      min: 0,
      max: 99,
      description: 'Nível de Exposição Paranormal do Agente.',
    },
    {
      id: 'agi',
      name: 'Agilidade',
      shortName: 'AGI',
      type: 'number',
      category: 'Atributos',
      defaultValue: 1,
      min: 1,
      max: 15,
      description: 'Destreza, velocidade e coordenação motora fina.',
    },
    {
      id: 'for',
      name: 'Força',
      shortName: 'FOR',
      type: 'number',
      category: 'Atributos',
      defaultValue: 1,
      min: 1,
      max: 15,
      description: 'Massa muscular, potência e poder destrutivo.',
    },
    {
      id: 'int',
      name: 'Intelecto',
      shortName: 'INT',
      type: 'number',
      category: 'Atributos',
      defaultValue: 1,
      min: 1,
      max: 15,
      description: 'Raciocínio lógico, erudição e dedução.',
    },
    {
      id: 'pre',
      name: 'Presença',
      shortName: 'PRE',
      type: 'number',
      category: 'Atributos',
      defaultValue: 1,
      min: 1,
      max: 15,
      description: 'Percepção, determinação, magnetismo e força de vontade.',
    },
    {
      id: 'vig',
      name: 'Vigor',
      shortName: 'VIG',
      type: 'number',
      category: 'Atributos',
      defaultValue: 1,
      min: 1,
      max: 15,
      description: 'Saúde, fôlego e resistência física a toxinas e impacto.',
    },
    {
      id: 'defesa',
      name: 'Defesa Passiva',
      type: 'derived',
      category: 'Combate',
      defaultValue: 10,
      formula: '10 + agi',
      description: 'Defesa base calculada como 10 + Agilidade.',
    },
    {
      id: 'esquiva',
      name: 'Esquiva',
      type: 'derived',
      category: 'Combate',
      defaultValue: 10,
      formula: '10 + agi * 2',
      description: 'Reação de esquiva ativa: Defesa + Agilidade.',
    },
    {
      id: 'bloqueio',
      name: 'Bloqueio (RD)',
      type: 'derived',
      category: 'Combate',
      defaultValue: 1,
      formula: 'vig',
      description: 'Redução de dano ao bloquear igual ao Vigor.',
    },
  ],

  skills: [
    { id: 'acrobacia', name: 'Acrobacia', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'adestramento', name: 'Adestramento', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'artes', name: 'Artes', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'atletismo', name: 'Atletismo', baseAttribute: 'for', type: 'proficiency' },
    { id: 'atualidades', name: 'Atualidades', baseAttribute: 'int', type: 'proficiency' },
    { id: 'ciencias', name: 'Ciências', baseAttribute: 'int', type: 'proficiency' },
    { id: 'crime', name: 'Crime', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'diplomacia', name: 'Diplomacia', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'enganacao', name: 'Enganação', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'fortitude', name: 'Fortitude', baseAttribute: 'vig', type: 'proficiency' },
    { id: 'furtividade', name: 'Furtividade', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'iniciativa', name: 'Iniciativa', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'intimidacao', name: 'Intimidação', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'intuicao', name: 'Intuição', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'investigacao', name: 'Investigação', baseAttribute: 'int', type: 'proficiency' },
    { id: 'luta', name: 'Luta', baseAttribute: 'for', type: 'proficiency' },
    { id: 'medicina', name: 'Medicina', baseAttribute: 'int', type: 'proficiency' },
    { id: 'ocultismo', name: 'Ocultismo', baseAttribute: 'int', type: 'proficiency' },
    { id: 'percepcao', name: 'Percepção', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'pilotagem', name: 'Pilotagem', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'pontaria', name: 'Pontaria', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'profissao', name: 'Profissão', baseAttribute: 'int', type: 'proficiency' },
    { id: 'reflexos', name: 'Reflexos', baseAttribute: 'agi', type: 'proficiency' },
    { id: 'religiao', name: 'Religião', baseAttribute: 'pre', type: 'proficiency' },
    { id: 'sobrevivencia', name: 'Sobrevivência', baseAttribute: 'int', type: 'proficiency' },
    { id: 'tatica', name: 'Tática', baseAttribute: 'int', type: 'proficiency' },
    { id: 'tecnologia', name: 'Tecnologia', baseAttribute: 'int', type: 'proficiency' },
    { id: 'vontade', name: 'Vontade', baseAttribute: 'pre', type: 'proficiency' },
  ],

  resources: [
    {
      id: 'pv',
      name: 'Pontos de Vida (PV)',
      maxFormula: '12 + vig * 3 + floor(nex / 5) * (3 + vig)',
      defaultValue: 15,
      color: '#ef4444',
      type: 'bar',
      description: 'Integridade física do agente.',
    },
    {
      id: 'pe',
      name: 'Pontos de Esforço (PE)',
      maxFormula: '2 + pre * 2 + floor(nex / 5) * (2 + pre)',
      defaultValue: 4,
      color: '#eab308',
      type: 'bar',
      description: 'Combustível para habilidades ativas e conjuração de rituais.',
    },
    {
      id: 'san',
      name: 'Sanidade (SAN)',
      maxFormula: '12 + pre * 3 + floor(nex / 5) * (3 + pre)',
      defaultValue: 15,
      color: '#3b82f6',
      type: 'bar',
      description: 'Estabilidade psicológica contra as bizarrices paranormais.',
    },
  ],

  combat: {
    initiativeFormula: '1d20 + agi',
    hpResource: 'pv',
    defenseStat: {
      name: 'Defesa',
      formula: '10 + agi',
    },
    conditions: [
      { id: 'abalado', name: 'Abalado (-1d20)', color: '#a855f7' },
      { id: 'alquebrado', name: 'Alquebrado (+1 PE gasto)', color: '#ec4899' },
      { id: 'atordoado', name: 'Atordoado', color: '#eab308' },
      { id: 'caido', name: 'Caído', color: '#64748b' },
      { id: 'enlouquecendo', name: 'Enlouquecendo (SAN = 0)', color: '#8b5cf6' },
      { id: 'morrendo', name: 'Morrendo (PV = 0)', color: '#ef4444' },
      { id: 'sangrando', name: 'Sangrando (1d6 dano)', color: '#dc2626' },
    ],
  },

  diceMacros: [
    { id: 'teste_1d20', name: 'Teste Simples 1d20', expression: '1d20' },
    { id: 'teste_2d20', name: 'Teste com 2d20 (Maior)', expression: '2d20kh1' },
    { id: 'teste_3d20', name: 'Teste com 3d20 (Maior)', expression: '3d20kh1' },
    { id: 'dano_sangue', name: 'Dano de Sangue (2d8)', expression: '2d8' },
  ],

  rollPresets: [
    { id: 'init', name: 'Iniciativa', expression: '1d20 + $agi' },
    { id: 'teste_atletismo', name: 'Teste de Força', expression: '1d20 + $for' },
    { id: 'teste_pontaria', name: 'Disparo de Arma de Fogo', expression: '1d20 + $agi' },
  ],

  itemCategories: ['Arma Branca', 'Arma de Fogo', 'Munição', 'Proteção / Colete', 'Item Amaldiçoado', 'Acessório', 'Item Tático'],
  createdAt: Date.now(),
  updatedAt: Date.now(),
};
