// ARCANA Official Preset — Tormenta20 (T20)
// Fully compliant with Bible Section 6

import type { SystemDefinition } from '@/types';

export const tormenta20System: SystemDefinition = {
  id: 'tormenta20',
  name: 'Tormenta20 (T20)',
  version: '1.4.0',
  author: 'Jambô Editora / ARCANA',
  icon: '⚔️',
  color: '#b91c1c',
  description: 'O maior RPG medieval fantástico do Brasil. Aventura épica no mundo de Arton com sistema de Pontos de Mana dinâmicos.',
  builtin: true,
  rollConvention: 'd20',

  attributes: [
    {
      id: 'nivel',
      name: 'Nível',
      shortName: 'NÍV',
      type: 'number',
      category: 'Geral',
      defaultValue: 1,
      min: 1,
      max: 20,
    },
    {
      id: 'for',
      name: 'Força',
      shortName: 'FOR',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
    },
    {
      id: 'des',
      name: 'Destreza',
      shortName: 'DES',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
    },
    {
      id: 'con',
      name: 'Constituição',
      shortName: 'CON',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
    },
    {
      id: 'int',
      name: 'Inteligência',
      shortName: 'INT',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
    },
    {
      id: 'sab',
      name: 'Sabedoria',
      shortName: 'SAB',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
    },
    {
      id: 'car',
      name: 'Carisma',
      shortName: 'CAR',
      type: 'number',
      category: 'Atributos',
      defaultValue: 10,
      min: 1,
      max: 30,
    },
    // Derived Modifiers
    {
      id: 'mod_for',
      name: 'Mod. Força',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((for - 10) / 2)',
    },
    {
      id: 'mod_des',
      name: 'Mod. Destreza',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((des - 10) / 2)',
    },
    {
      id: 'mod_con',
      name: 'Mod. Constituição',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((con - 10) / 2)',
    },
    {
      id: 'mod_int',
      name: 'Mod. Inteligência',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((int - 10) / 2)',
    },
    {
      id: 'mod_sab',
      name: 'Mod. Sabedoria',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((sab - 10) / 2)',
    },
    {
      id: 'mod_car',
      name: 'Mod. Carisma',
      type: 'derived',
      category: 'Modificadores',
      defaultValue: 0,
      formula: 'floor((car - 10) / 2)',
    },
    {
      id: 'defesa',
      name: 'Defesa',
      type: 'derived',
      category: 'Combate',
      defaultValue: 10,
      formula: '10 + mod_des',
    },
  ],

  skills: [
    { id: 'acrobacia', name: 'Acrobacia', baseAttribute: 'des', type: 'proficiency' },
    { id: 'adestramento', name: 'Adestramento', baseAttribute: 'car', type: 'proficiency' },
    { id: 'atletismo', name: 'Atletismo', baseAttribute: 'for', type: 'proficiency' },
    { id: 'atuacao', name: 'Atuação', baseAttribute: 'car', type: 'proficiency' },
    { id: 'cavalgar', name: 'Cavalgar', baseAttribute: 'des', type: 'proficiency' },
    { id: 'conhecimento', name: 'Conhecimento', baseAttribute: 'int', type: 'proficiency' },
    { id: 'cura', name: 'Cura', baseAttribute: 'sab', type: 'proficiency' },
    { id: 'diplomacia', name: 'Diplomacia', baseAttribute: 'car', type: 'proficiency' },
    { id: 'enganacao', name: 'Enganação', baseAttribute: 'car', type: 'proficiency' },
    { id: 'fortitude', name: 'Fortitude', baseAttribute: 'con', type: 'proficiency' },
    { id: 'furtividade', name: 'Furtividade', baseAttribute: 'des', type: 'proficiency' },
    { id: 'guerra', name: 'Guerra', baseAttribute: 'int', type: 'proficiency' },
    { id: 'iniciativa', name: 'Iniciativa', baseAttribute: 'des', type: 'proficiency' },
    { id: 'intimidacao', name: 'Intimidação', baseAttribute: 'car', type: 'proficiency' },
    { id: 'intuicao', name: 'Intuição', baseAttribute: 'sab', type: 'proficiency' },
    { id: 'investigacao', name: 'Investigação', baseAttribute: 'int', type: 'proficiency' },
    { id: 'jogatina', name: 'Jogatina', baseAttribute: 'car', type: 'proficiency' },
    { id: 'ladinagem', name: 'Ladinagem', baseAttribute: 'des', type: 'proficiency' },
    { id: 'luta', name: 'Luta', baseAttribute: 'for', type: 'proficiency' },
    { id: 'misticismo', name: 'Misticismo', baseAttribute: 'int', type: 'proficiency' },
    { id: 'nobreza', name: 'Nobreza', baseAttribute: 'int', type: 'proficiency' },
    { id: 'oficio', name: 'Ofício', baseAttribute: 'int', type: 'proficiency' },
    { id: 'percepcao', name: 'Percepção', baseAttribute: 'sab', type: 'proficiency' },
    { id: 'pilotagem', name: 'Pilotagem', baseAttribute: 'des', type: 'proficiency' },
    { id: 'pontaria', name: 'Pontaria', baseAttribute: 'des', type: 'proficiency' },
    { id: 'reflexos', name: 'Reflexos', baseAttribute: 'des', type: 'proficiency' },
    { id: 'religiao', name: 'Religião', baseAttribute: 'sab', type: 'proficiency' },
    { id: 'sobrevivencia', name: 'Sobrevivência', baseAttribute: 'sab', type: 'proficiency' },
    { id: 'vontade', name: 'Vontade', baseAttribute: 'sab', type: 'proficiency' },
  ],

  resources: [
    {
      id: 'pv',
      name: 'Pontos de Vida (PV)',
      maxFormula: '16 + mod_con + (nivel - 1) * (4 + mod_con)',
      defaultValue: 16,
      color: '#ef4444',
      type: 'bar',
    },
    {
      id: 'pm',
      name: 'Pontos de Mana (PM)',
      maxFormula: '4 + (nivel - 1) * 4',
      defaultValue: 4,
      color: '#3b82f6',
      type: 'bar',
    },
  ],

  combat: {
    initiativeFormula: '1d20 + mod_des',
    hpResource: 'pv',
    defenseStat: {
      name: 'Defesa',
      formula: '10 + mod_des',
    },
    conditions: [
      { id: 'abalado', name: 'Abalado', color: '#a855f7' },
      { id: 'abestalhado', name: 'Abestalhado', color: '#eab308' },
      { id: 'cego', name: 'Cego', color: '#6b7280' },
      { id: 'confuso', name: 'Confuso', color: '#ec4899' },
      { id: 'fatigado', name: 'Fatigado', color: '#f59e0b' },
      { id: 'indefeso', name: 'Indefeso', color: '#ef4444' },
      { id: 'sangrando', name: 'Sangrando', color: '#dc2626' },
    ],
  },

  diceMacros: [
    { id: 'd20_teste', name: 'Teste d20', expression: '1d20' },
    { id: 'dano_espada', name: 'Espada Longa (1d8)', expression: '1d8' },
    { id: 'dano_critico', name: 'Crítico x2 (2d8)', expression: '2d8' },
  ],

  rollPresets: [
    { id: 'iniciativa', name: 'Iniciativa', expression: '1d20 + $mod_des' },
    { id: 'ataque_luta', name: 'Teste de Luta', expression: '1d20 + $mod_for' },
    { id: 'ataque_pontaria', name: 'Disparo à Distância', expression: '1d20 + $mod_des' },
  ],

  itemCategories: ['Arma', 'Armadura', 'Escudo', 'Item Mágico', 'Alquimia', 'Equipamento de Aventura'],
  createdAt: Date.now(),
  updatedAt: Date.now(),
};
